# syntax=docker/dockerfile:1
FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:main AS toolchain

FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    cmake \
    libclang-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=toolchain /usr/local/ /usr/local/
COPY --from=toolchain /base-runner.sh /base-runner.sh
COPY --from=toolchain /opt/toolchain.cmake /opt/toolchain.cmake
COPY --from=toolchain /usr/bin/x86_64-linux-musl-gcc.sh /usr/bin/x86_64-linux-musl-gcc.sh

ENV CROSS_TOOLCHAIN_PREFIX=x86_64-linux-musl- \
    CROSS_SYSROOT=/usr/local/x86_64-linux-musl \
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-musl-gcc.sh \
    AR_x86_64_unknown_linux_musl=x86_64-linux-musl-ar \
    CC_x86_64_unknown_linux_musl=x86_64-linux-musl-gcc \
    CXX_x86_64_unknown_linux_musl=x86_64-linux-musl-g++ \
    CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_musl=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_musl="--sysroot=/usr/local/x86_64-linux-musl" \
    QEMU_LD_PREFIX=/usr/local/x86_64-linux-musl \
    RUST_TEST_THREADS=1 \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
    CROSS_CMAKE_CRT=musl \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC" \
    CROSS_BUILTINS_PATCHED_MINOR_VERSION=48

CMD ["/bin/bash"]
