FROM nousresearch/hermes-agent:latest

USER hermes
WORKDIR /home/hermes

COPY --chmod=755 hermes-agent/init /usr/local/bin/init
COPY --chmod=755 hermes-agent/entrypoint /usr/local/bin/entrypoint

ENTRYPOINT ["entrypoint"]