version: "2"

configs:
  init_script:
    file: /path/to/your/init/script
  picoclaw_config:
    file: /path/to/your/config.json

volumes:
  home:
  workspace:

services:
  nullclaw:
    image: ilteoood/nullclaw
    container_name: nullclaw
    environment:
      - NULLCLAW_MODE=gateway
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    ports:
      - "3000:3000"
    restart: unless-stopped
  zeroclaw:
    image: ilteoood/zeroclaw
    container_name: zeroclaw
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    ports:
      - "42617:42617"
    restart: unless-stopped
  picoclaw:
    image: ilteoood/picoclaw
    container_name: picoclaw
    environment:
      - PICOCLAW_MODE=gateway
    volumes:
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
      - source: picoclaw_config
        target: /root/.picoclaw/config.json
        mode: 0644
    restart: unless-stopped
  opencode:
    image: ilteoood/opencode
    container_name: opencode
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    restart: unless-stopped
  claude-code:
    image: ilteoood/claude-code
    container_name: claude-code
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    restart: unless-stopped
  codex:
    image: ilteoood/codex
    container_name: codex
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    restart: unless-stopped
  openclaw:
    image: ilteoood/openclaw
    container_name: openclaw
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    ports:
      - "18789:18789"
    restart: unless-stopped
  openfang:
    image: ilteoood/openfang
    container_name: openfang
    volumes:
      - workspace:/home/workspace
    restart: unless-stopped
  copilot-cli:
    image: ilteoood/copilot-cli
    container_name: copilot-cli
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    restart: unless-stopped
  hermes-agent:
    image: ilteoood/hermes-agent
    container_name: hermes-agent
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    restart: unless-stopped
